ALTER TABLE :schema.products ADD COLUMN IF NOT EXISTS stock INT;
ALTER TABLE :schema.products ADD COLUMN IF NOT EXISTS track_stock BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE :schema.settings ADD COLUMN IF NOT EXISTS inventory_enabled BOOLEAN DEFAULT FALSE NOT NULL;
